trigger:
- main

resources:
- repo: self

variables:
  azureSubscription: 'Suscripción 1'
  containerRegistry: 'focoanalitics.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imageName: 'focoblog:$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        tags: |
          $(imageName)

- stage: Push
  dependsOn: Build
  jobs:
  - job: Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Log in to Docker registry
      inputs:
        command: login
        containerRegistry: $(containerRegistry)
        dockerRegistryEndpoint: $(azureSubscription)
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        command: push
        repository: $(containerRegistry)/focoblog
        tags: |
          $(imageName)

- stage: Deploy
  dependsOn: Push
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: $(Suscripción 1)
        appName: 'focoanalytics'
        containers: '$(containerRegistry)/focoblog:$(imageName)'
