# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - focoanalytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ec59eeda7f764fdc9002a1661199bcfd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_65c316f9b1614da0bb22d4d4ce9fcf83 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ec59eeda7f764fdc9002a1661199bcfd }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'focoanalytics'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5977b75b60c84c53acc3bd0c79951b31 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ec59eeda7f764fdc9002a1661199bcfd }}/appsvc/staticsite:${{ github.sha }}'