# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pruebassssss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_3b02d38c506849ef808b90cf0f731c69 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_293b7f309b8b42dfbe834248d186c050 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3b02d38c506849ef808b90cf0f731c69 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pruebassssss'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_150574852e854746a8cbe13e13b9c1e5 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3b02d38c506849ef808b90cf0f731c69 }}/appsvc/staticsite:${{ github.sha }}'